{
 "title": "Coronavirus",
 "time": { "from": "now/fy", "to": "now/fy" },
 "templating": {
  "list": [
   { "name": "pais", "label": "Country", "query": "France" },
   {
    "name": "lastupdate",
    "query": "\tSELECT max(Last_Update) FROM `covid-336715.datoscovid.datos`"
   },
   {
    "name": "casostotales",
    "query": "SELECT   sum(`Confirmed`) as total\nFROM `covid-336715.datoscovid.datos`\nWHERE\n  Country_Region = '$pais' "
   },
   { "name": "dias", "query": "28,14,7" },
   {
    "name": "comunidades",
    "query": "Andalusia,Aragon,Asturias,Baleares,C.Valenciana,Canarias,Cantabria,Castilla - La Mancha,Castilla y Leon, Catalonia,Ceuta,Extremadura,Galicia,La Rioja,Madrid,Melilla,Murcia,Navarra,Pais Vasco"
   },
   {
    "name": "data",
    "query": "select DATE_SUB(Date(Fecha), INTERVAL 1 Day) \nfrom `covid-336715.datoscovid.datos` \n"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "description": "at (YYYY-MM-DDTH:M:S)",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "options": {
    "content": "# ACTUALIZADO ÚLTIMA VEZ:\n${lastupdate}"
   },
   "targets": [
    {
     "dataset": "datoscovid",
     "orderByCol": "1",
     "orderBySort": "1",
     "partitionedField": "Fecha",
     "project": "covid-336715",
     "rawSql": "SELECT\n  time_column,\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "El Mundo",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "SELECT sum(Confirmed) as Casos_Confirmados, sum(Deaths) as Muertes FROM `covid-336715.datoscovid.datos` where Date(Fecha) = DATE_SUB(CURRENT_DATE(), INTERVAL 1 Day)"
    }
   ]
  },
  {
   "title": "$pais",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "SELECT Country_Region, sum(Confirmed) as Casos_Confirmados, sum(Deaths) as Muertes FROM `covid-336715.datoscovid.datos` where Date(Fecha) = DATE_SUB(CURRENT_DATE(), INTERVAL 1 Day) and Country_Region = '$pais' GROUP BY Country_Region"
    }
   ]
  },
  {
   "title": "Casos Totales por día en España",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 5 },
   "targets": [
    {
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "SELECT date(d1.Fecha) as time, (sum(d1.Confirmed)-sum(d2.Confirmed)) as Confirmados\nFROM `covid-336715.datoscovid.datos` d1, `covid-336715.datoscovid.datos` d2 \nWHERE Date(d2.Fecha) = DATE_SUB(Date(d1.Fecha), INTERVAL 1 Day)\nand d1.Country_Region = d2.Country_Region \nand d1.Province_State = d2.Province_State\nand d1.Country_Region='Spain'\nGROUP BY time order by time,Confirmados"
    }
   ]
  },
  {
   "title": "Mapamundi",
   "type": "geomap",
   "gridPos": { "h": 15, "w": 14, "x": 10, "y": 5 },
   "targets": [
    {
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "SELECT d.Province_State, d.Country_Region, i.Lat, i.Long_, d.Incident_Rate,d.Confirmed, d.Deaths\nFROM `covid-336715.datoscovid.datos` d, `covid-336715.datoscovid.info` i \nWHERE d.Province_State = i.Province_State and d.Country_Region = i.Country_Region and Date(d.Fecha) = DATE_SUB(CURRENT_DATE(), INTERVAL 1 Day)"
    }
   ]
  },
  {
   "title": "Casos Totales por día en el Pais Vasco",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 12 },
   "targets": [
    {
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "SELECT date(d1.Fecha) as time, (sum(d1.Confirmed)-sum(d2.Confirmed)) as Confirmados\nFROM `covid-336715.datoscovid.datos` d1, `covid-336715.datoscovid.datos` d2 \nWHERE Date(d2.Fecha) = DATE_SUB(Date(d1.Fecha), INTERVAL 1 Day)\nand d1.Country_Region = d2.Country_Region \nand d1.Province_State = d2.Province_State\nand d1.Province_State='Pais Vasco'\nGROUP BY time order by time,Confirmados"
    }
   ]
  },
  {
   "title": "Casos en $comunidades los últimos $dias dias",
   "type": "bargauge",
   "description": "Estos datos son ACUMULADOS",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "select Confirmed, Date(Fecha) as Fecha \nfrom `covid-336715.datoscovid.datos` \nwhere Province_State='$comunidades' \nand DATE(Fecha)< current_date() \nand DATE(Fecha) > DATE_SUB(current_date(), INTERVAL $dias+1 DAY) ORDER BY Fecha"
    }
   ]
  },
  {
   "title": "Casos covid en las Comunidades Españolas",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 }
  },
  {
   "title": "Andalucía",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "SELECT  Confirmed\nFROM `covid-336715.datoscovid.datos`\nWHERE Province_State= 'Andalusia' and Last_Update='$lastupdate'"
    }
   ]
  },
  {
   "title": "Aragón",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "SELECT  Confirmed\nFROM `covid-336715.datoscovid.datos`\nWHERE Province_State= 'Aragon' and Last_Update='$lastupdate'"
    }
   ]
  },
  {
   "title": "Melilla",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "SELECT  Confirmed\nFROM `covid-336715.datoscovid.datos`\nWHERE Province_State= 'Melilla' and Last_Update='$lastupdate'\n LIMIT 874"
    }
   ]
  },
  {
   "title": "Murcia",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "SELECT  Confirmed\nFROM `covid-336715.datoscovid.datos`\nWHERE Province_State= 'Murcia' and Last_Update='$lastupdate'\n LIMIT 874"
    }
   ]
  },
  {
   "title": "Islas Canarias",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "SELECT  Confirmed\nFROM `covid-336715.datoscovid.datos`\nWHERE Province_State= 'Canarias' and Last_Update='$lastupdate'\n LIMIT 874"
    }
   ]
  },
  {
   "title": "Cantabria",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "SELECT  Confirmed\nFROM `covid-336715.datoscovid.datos`\nWHERE Province_State= 'Cantabria' and Last_Update='$lastupdate'\n LIMIT 874"
    }
   ]
  },
  {
   "title": "Principado de Asturias",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "SELECT  Confirmed\nFROM `covid-336715.datoscovid.datos`\nWHERE Province_State= 'Asturias' and Last_Update='$lastupdate'\n"
    }
   ]
  },
  {
   "title": "Castilla y León",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "SELECT  Confirmed\nFROM `covid-336715.datoscovid.datos`\nWHERE Province_State= 'Castilla y Leon' and Last_Update='$lastupdate'\n LIMIT 874"
    }
   ]
  },
  {
   "title": "Cataluña",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "SELECT  Confirmed\nFROM `covid-336715.datoscovid.datos`\nWHERE Province_State= 'Catalonia' and Last_Update='$lastupdate'\n LIMIT 874"
    }
   ]
  },
  {
   "title": "Ceuta",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "SELECT  Confirmed\nFROM `covid-336715.datoscovid.datos`\nWHERE Province_State= 'Ceuta' and Last_Update='$lastupdate'\n LIMIT 874"
    }
   ]
  },
  {
   "title": "Castilla la Mancha",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "SELECT  Confirmed\nFROM `covid-336715.datoscovid.datos`\nWHERE Province_State= 'Castilla - La Mancha' and Last_Update='$lastupdate'\n LIMIT 874"
    }
   ]
  },
  {
   "title": "Galicia",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "SELECT  Confirmed\nFROM `covid-336715.datoscovid.datos`\nWHERE Province_State= 'Galicia' and Last_Update='$lastupdate'\n LIMIT 874"
    }
   ]
  },
  {
   "title": "La Rioja",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "SELECT  Confirmed\nFROM `covid-336715.datoscovid.datos`\nWHERE Province_State= 'La Rioja' and Last_Update='$lastupdate'\n LIMIT 874"
    }
   ]
  },
  {
   "title": "Madrid",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "SELECT  Confirmed\nFROM `covid-336715.datoscovid.datos`\nWHERE Province_State= 'Madrid' and Last_Update='$lastupdate'\n LIMIT 874"
    }
   ]
  },
  {
   "title": "Extremadura",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "SELECT  Confirmed\nFROM `covid-336715.datoscovid.datos`\nWHERE Province_State= 'Extremadura' and Last_Update='$lastupdate'\n LIMIT 874"
    }
   ]
  },
  {
   "title": "Islas Baleares",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "SELECT  Confirmed\nFROM `covid-336715.datoscovid.datos`\nWHERE Province_State= 'Baleares' and Last_Update='$lastupdate'\n LIMIT 874"
    }
   ]
  },
  {
   "title": "Comunidad Foral de Navarra",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "SELECT  Confirmed\nFROM `covid-336715.datoscovid.datos`\nWHERE Province_State= 'Navarra' and Last_Update='$lastupdate' \n "
    }
   ]
  },
  {
   "title": "País Vasco",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "SELECT  Confirmed\nFROM `covid-336715.datoscovid.datos`\nWHERE Province_State= 'Pais Vasco' and Last_Update='$lastupdate'\n LIMIT 874"
    }
   ]
  },
  {
   "title": "Comunidad Valenciana",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "SELECT  Confirmed\nFROM `covid-336715.datoscovid.datos`\nWHERE Province_State= 'C. Valenciana' and Last_Update='$lastupdate'\n LIMIT 874"
    }
   ]
  }
 ]
}